<?php
session_start();
include_once('fonction.php');
if(isset($_POST['valider'])){
    $phrase = $_POST['phrase'];
    $erreur=[];
    estValide($phrase,"erreur",$erreur);
    if(count($erreur)==0){   
      deletEspace($phrase);
      deletCareEsp($phrase);
      deletEsBefor($phrase);
      setcookie("phrase",$phrase);
      header('location:index.php');
    }else{
        lonPhrase($phrase);
        $_SESSION['erreur']=$erreur;
        $_SESSION['post']=$_POST;
        header('location:index.php');
    }
}
?>